const ADD = 'ADD';
const CLEAR = 'CLEAR';
const CARD_CLICK = 'CARD_CLICK';
const RENAMING = 'RENAMING';
const RENAMED = 'RENAMED';
const RESET = 'RESET';

export { ADD, CLEAR, CARD_CLICK, RENAMING, RENAMED, RESET };
