const ADD = 'ADD';
const CLEAR = 'CLEAR';
const SORT = 'SORT';
const RESET = 'RESET';

const CARD_CLICK = 'CARD_CLICK';

const RENAMING = 'BOARD_RENAMING';
const RENAMED = 'BOARD_RENAMED';

export { ADD, CLEAR, SORT, RESET, CARD_CLICK, RENAMING, RENAMED };
